# Copyright 2024 HM Revenue & Customs
#

include "backend.conf"

# This is the main configuration file for the application.
# ~~~~~

appName = block-and-signals-gds-store

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

# Play Modules
play.modules.enabled += "uk.gov.hmrc.blockandsignalsgdsstore.config.Module"

play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"

# The application languages
# ~~~~~
play.i18n.langs = ["en"]

# Router
# ~~~~~
# Define the Router object to use for this application.
# This router will be looked up first when the application is starting up,
# so make sure this is the entry point.
# Furthermore, it's assumed your route file is named properly.
# So for an application router like `my.application.Router`,
# you may need to define a router file `conf/my.application.routes`.
# Default to Routes in the root package (and conf/routes)
# !!!WARNING!!! DO NOT CHANGE THIS ROUTER
play.http.router = prod.Routes

play.filters.enabled += play.filters.gzip.GzipFilter

play.filters.gzip.contentType.whiteList = [
    "application/x-ndjson"
]

# Microservice specific config

mongodb {
  uri = "mongodb://localhost:27017/block-and-signals-gds-store"
}

microservice {
  services {
    auth {
      host = localhost
      port = 8500
    }
  }
}

event-ttl = 548.days

search.result.limit = 100000
search.result.mongo-batch-size = 1000
search.result.chunk-size = 500
search.result.chunk-window = 150.millis
search.request.max-allowed-ids = 20
search.request.max-allowed-cred-ids = 20
search.request.max-allowed-subject-ids = 20

test-only.event-generator.insert-group-size = 500
test-only.event-generator.insert-parallelism = 2
test-only.event-generator.view-update-group-size = 50
test-only.event-generator.view-update-parallelism = 2

user-agent-allow-list = ["block-and-signals-frontend", "signal-processor"]

feature {
  gds-api-v2.enabled = false
  v1-search.use-view = true
}
